server:
  port: 8888

spring:
  application:
    name: config-server

# Common configurations (if any)
common:
  message: "Welcome to the projectOne architecture"

# Product Service Configuration
product-service:
  server:
    port: 8083
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/projectOne
      username: postgres
      password: dinesh12345
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

# User Service Configuration
user-service:
  server:
    port: 8084
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/userDB
      username: root
      password: user@123
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

# Inventory Service Configuration
inventory-service:
  server:
    port: 8085
  spring:
    datasource:
      url: jdbc:h2:mem:inventoryDB
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
