server:
  port: 8089

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://prod-db-url:5432/projectOne_prod
    username: postgres
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
