server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userDB
    username: root
    password: user@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
